name: Stay Online Bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install StreamYard Package
        # سنقوم بتثبيت المكتبة اللازمة يدوياً لأن ملف package.json مفقود
        run: npm install discord.js node-fetch@2

      - name: Run the bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: node bot.js
